### PR TITLE
Create window by functional return of parameters

### PR DESCRIPTION
**Pull request by tavurth**
I found it restricting that the arguments to `with-init-window` should be a hard-coded list.

```lisp
(defun my-parameter-generator () 
  '(:width 100 :height 100 :title "My Test Window"))

(with-init-window-from-list (my-parameter-generator)
  (loop ...))
```
Or:
```lisp
(with-init-window-from-list (list :width 100 :height 100 :title "My title")
  (loop ...))
```

### CODE REVIEW

**Comment by AlexCharlton** [comment]
Cool! Is it just me, or could these macros straight up replace `with-window` and `with-init-window` without changing their contracts?

Thanks!

**Comment by tavurth** [comment]
Unfortunately it would cause breaking changes to the current examples:

**Comment by AlexCharlton** [comment]
Sounds good 👍

**Comment by tavurth** [comment]
So, passing dynamic parameters is a headache, because we use the rest parameter to catch all parameters in a list style, the macro doesn't expand well.

Add to the fact that we're usually nesting it within several layers of other macros (with-body-in-main-thread), and it seems to fail correct compilation every time.

The examples weren't working, as they were all in a global package. I fixed them, and added package-names showing where each function is getting called from.

I added a ./examples/run-all.lisp script to test all the current examples.

**Comment by tavurth** [comment]
This should work, but doesn't inside the parent macros:

```
(defun called-before (&rest keys)
  (format t "Called before: ~A~%" keys))

(defun called-inside ()
  (format t "Called inside~%"))

(defun called-after ()
  (format t "Called after~%"))

(defun callback (&rest rest)
  '("Hello"))

(defmacro resolve-list ((&rest keys) &body body)
  (cond
    ((fboundp (car keys))
     `(unwind-protect
           (progn
             (apply #'called-before ,keys)
             ,@body)
        (called-after)))

    ((typep (car keys) 'symbol)
     `(unwind-protect
           (progn
             (called-before ,@keys)
             ,@body)
        (called-after)))))

(resolve-list
    (:test 123)
  (called-inside))

(resolve-list
    (callback 12 3)
  (called-inside))
```

**Pull request closed without merging**
